# Generated by Django 4.1.3 on 2023-02-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_pinjam_tgl_kembali_alter_pinjam_tgl_pinjam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinjam',
            name='obat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.jenis'),
        ),
    ]
