# Generated by Django 4.1.3 on 2023-02-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_obat_id_pinjam_judul_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nama',
            new_name='judul',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='jenis_id',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='kodebrg',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='link_gbr',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='waktu_posting',
        ),
        migrations.AddField(
            model_name='barang',
            name='kodebuku',
            field=models.CharField(default='Jdl', max_length=8),
        ),
    ]
